server:
  port: 9494
  servlet:
    context-path: /kafka
spring:
  application:
    name: spring-kafka-event-stream

  kafka:
    consumer:
      group-id: my-group-id
    producer:
      bootstrap-servers: localhost:19092
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
